### ISSUE TITLE
redundant phpdoc comment tag with generics

### ISSUE THREAD

**Issue by orklah** [funivan/PhpClean#112]
Hi,

This inspections flags all doc tags like:
`@param array<int>` as redundant given a parameter with `array` type in signature.

The inference engine in phpstorm just strips those and don't consider them at all. Could it be possible to add an edge case in phpClean for every type with generics notaton `type<subtype>`?

Thanks

**Comment by funivan** [comment]
I think that a phpstorm does not support `array<int>` notation.
If you need to specify list of items you can use `@param string[]`

Can you show a document/help/topic about this notation in phpstorm?

**Comment by orklah** [comment]
This is the current status on PHPStorm side:
https://youtrack.jetbrains.com/issue/WI-43843

They're working on Psalm/PHPStan integration through plugin so maybe this will move but I don't know what impact this could have on your plugin.

I was kinda hoping that this could have been patched on your side, but if it's not possible, you can close this issue :)

**Comment by funivan** [comment]
When you are using psalm/phpstan then it is better to disable phpstorm instpections because phpstorm does not resolve doc comments in the right way, it is just pass data to the `plugin` and get results from it. 
I can use some dirty hacks to resolve this issue, but IMHO this is a wrong way. 

Also you can tale a look on [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer), they also have some fixers to remove redundant comments.
I will close this issue right now. When we will get native generics in php I will revisit this rules.

**Comment by orklah** [comment]
Hey!

Jetbrains just released a new EAP with psalm and phpstan integration.

It now reads generics annotations. Could you revisit this issue?

**Comment by funivan** [comment]
> Hey!
> 
> Jetbrains just released a new EAP with psalm and phpstan integration.
> 
> It now reads generics annotations. Could you revisit this issue?

Yes, this is awesome news for us. Will check it.
