### ISSUE TITLE
Change VirtualTypeCheck to not propose `assert()`

### ISSUE THREAD

**Issue by lukaslangen** [funivan/PhpClean#144]
The README page says, that one should use php's built-in `assert()` function instead of a doc comment.

While I agree, that one should put an actual type check in the code and not just assume the type, I don't think `assert()` is the right way.

As taken from the [php documentation](https://www.php.net/manual/en/function.assert.php)

```
 Assertions should be used as a debugging feature only. You may use them for sanity-checks that test for conditions that should always be true and that indicate some programming errors if not or to check for the presence of certain features like extension functions or certain system limits and features.

Assertions should not be used for normal runtime operations like input parameter checks. As a rule of thumb your code should always be able to work correctly if assertion checking is not activated. 
```

It seems to me, that the current VirtualTypeCheck promotes somewhat of a bad practice, as it is not recommended to use `assert` in production code. There is even a [configuration option](https://www.php.net/manual/en/ini.core.php#ini.zend.assertions) intended for production environments where the actual code is not even generated anymore.

I propose to either remove the check alltogether or go ahead and tell the user about libraries that handle this case like `webmozart/assert`

**Comment by orklah** [comment]
I don't understant the quote you posted the same way as you
> You may use them for sanity-checks that test for conditions that should always be true and that indicate some programming errors

It's exactly what we're doing here. If there's a docblock with a specific type, it may be replaced with an assert that will state that we have this type or else, it's a programming error.

> Assertions should not be used for normal runtime operations like input parameter checks

Same, the goal here is not to check if we have the good type but to state it in a way that will crash in dev

> As a rule of thumb your code should always be able to work correctly if assertion checking is not activated. 

This rule stay true as well, the code will run the same with a disabled assert than with a docblock

webmozart\assert is great but it serve a larger purpose, it is used to check inputs on production code. This is way more strict than a docblock or an assert() and way more risky too if you don't have complete trust in your phpdoc (because assert() will only crash in dev)

**Comment by lukaslangen** [comment]
Thanks for your fast reply!

I see. And in the end you are correct as PhpClean is a 'static-code-analysis' tool.

However it can cause confusion. If you don't know yet, that `assert()` exists, you could come to the conclusion, that it's also a valid choice for input validation in production code, because it's not just a comment. And to be honest I've seen that quite often in the past.

Maybe we could add a more detailed description or something like a "Beware" block in the Readme? I'd be happy to do so myself, if anyone else than me thinks it might help :)

**Comment by funivan** [comment]
@lukaslangen thank you very much for the issue. It is really debatable and we (PHP developers) have tons of different workflows for checking types. 

The main goal of this inspection was to forbid people to use virtual doc types. Because they mean nothing. They are only helpers for PhpStorm. Then I have added quick fix to use the assert statement.

I see 3 valid options how to improve this inspection and remove confusions:
 - Remove Quick Fix totally. Users will be forced to chose another strategy. And we will not promote default `asserts`. 
 - Add some info about `webmozart/assert` library 
 - Describe how and in what way we should check our types (with different libraries, or with default asserts and how they can be configured)

Would be awesome if you can provide some useful blog posts. Contributions are always welcome, we can combine different options and make the plugin a little bit better.

**Comment by funivan** [comment]
@lukaslangen imagine you have asserts in your code and the following configuration:
`zend.assertions = -1` in production and `zend.assertions = 1` in non-production environment. 

Then you will have the following benefits: on non-production environment you can catch invalid types (assert function will do this)
In the production environment, you will have zero cost of asserts.

Using this workflow you get some benefits using asserts.


With comments (aka virtual types) you would not see any warning on production and non-production environments, because they do not validate anything.

IMHO it is good to have this inspection. But feel free to disable it.
