### ISSUE TITLE
False positive on superglobals.

### ISSUE THREAD

**Issue by MarcinOrlowski** [funivan/PhpClean#82]
Your plugin complain on use of `$_GET`, `$_SERVER` with "Deprecated global variable usage" which is pretty nonsense, as neither `$_GET`, nor `$_POST` nor `$_SERVER` etc are deprecated.

**Comment by funivan** [comment]
For example we are using symfony HTTP component to work with the request:
```
use Symfony\Component\HttpFoundation\Request;
$request = Request::createFromGlobals();
$request->query->get('page'); // valid
$_GET['page'] // invalid
```
Develoeprs should not access request data via superglobal `$_GET`. We should use only `$request` object.
If we use superglobals than we use global state (as we know the global state is bad)
So this inspection guarantee that the developer use only `request object` in the controller.
You can use the symfony request or any other implementations that encapsulate global data.

P.S. Feel free to disable this inspection.

**Comment by MarcinOrlowski** [comment]
But how this is even relevant? is this tool generic Php SA or Symfony dedicated? If this is the latter, just make it clear from start (ps you know where symfony gets the data to populate `$request` from, right :). 

For now you have "inspections", backed by completely made up argument about superglobals depreciation. It's hard to treat such tool seriously. Additionally it seems it's php 7 only as I saw reports about missing arg or return values hints and i did not see this documented.

**Comment by orklah** [comment]
This plugins is explictly dedicated to Strict rules in PHP. Having countless $_GET in the core of the code is really not a best practice, so this plugin do what it says.

This inspection can be useful for project with framework who provide better tools to access HTTP params but you're free to disable it in your settings if it doesn't suit your needs.

And yes, it does indeed assume you're in PHP 7, if you're not, you should disable return values and missing args inspections as well.

**Comment by funivan** [comment]
@MarcinOrlowski these inspections are not directly relative to the symfony or any other framework. 
We use this plugin in a different project with and without frameworks.
1. There are a lot of topics why global state is bad. We try to avoid it
2. Yes, this plugin supports only php 7 and latest. Fill free to disable some inspections. 
php 5.6 is not supported anymore. And php 7.0 get only security fixes. 
View more info https://www.php.net/supported-versions.php

**Comment by gisforgirard** [comment]
I really don't understand this, and can't find anywhere to back up that this is actually deprecated. 
https://stackoverflow.com/questions/18049232/are-get-and-post-being-phased-out-in-php

**Comment by funivan** [comment]
@gisforgirard global state is evil: https://softwareengineering.stackexchange.com/questions/148108/why-is-global-state-so-evil

For example `$_GET` is a global variable which can be modified from any place. If you modify `$_GET` from views, then our program can have an unpredictable state and it will be hard to debug/fix. 

If you know how to deal with it then you can disable this inspection.

**Comment by coins2yap** [comment]
It seems you are conflating global with superglobal. It's very rare that any superglobal is planned for deprecation - HTTP_SESSION_VARS was deprecated a while a go but this inspection is frankly, retarded because it is complaining about deprecated 'global' variables that are not in fact globals. It's a false warning. If any of the superglobals were in fact being deprecated, the warning would make sense for those superglobals that are ACTUALLY being deprecated. But that's not the case. And the response here is to basically point fingers at those who raise the issue, claiming that they're bad coders. Almost funny. The php language itself is making these superglobals available so that they can be used all over one's code.

The alternative would be to copy around superglobal values into local variables so as not to offend this code inspection tool (apparently). But however one did this, it would trigger the false warning that a superglobal variable is deprecated when in fact it isn't. 

I'm not going to disable the inspection because there is no ability to do so. What I'm going to do is disable this plugin. It's puking nonsense all over my files in the IDE(IntelliJ Idea)  and telling me repeatedly that $_SESSION is deprecated. Say what? Get real.

**Comment by orklah** [comment]
@coins2yap in the time it took you to type that, you could have learn to disable a specific inspection: https://www.jetbrains.com/help/phpstorm/disabling-and-enabling-inspections.html#suppress-inspections

Claiming everything PHP make available should be used as extensibly as possible is just weird, but feel free to use `goto` and `$_GLOBALS` if you want!

But there is one time you crossed the line and calling a free plugin that you can install if you want and disable at will 'retarded' is just wrong. You may not want to use this inspection but it exists for a reason and it's used by countless projects. The fact that YOU don't need it doesn't make it useless.

You took the time to come here, to insult the author and to tell him that you will stop using his free plugin, you're pathetic and I hope you'll come back here again to apologize.

**Comment by coins2yap** [comment]
It's not weird at all. The inspection complains about deprecated globals which aren't superglobals. And it was the author who insulted those who complained by saying that the inspection is really telling them that they're engaged in bad coding practices. 

The inspection is retarded and false. The variables being complained about are not globals nor are they being deprecated. It's plain wrong and telling people they're bad programmers for saying that the software is erroneously reporting deprecations is an insult. 

How hard would it have been to just admit that the inspection is wrong?

**Comment by coins2yap** [comment]
I will add here too that the inspection is not telling the programmer that his modification of a superglobal value is possibly in error, the inspection warns that the mere use of a superglobal is wrong because that superglobal is deprecated (while claiming it is a global). Merely checking the value of $_GET['some_value'] will trigger the warning. To call this retarded is totally appropriate.

**Comment by orklah** [comment]
So, your argument for example is that Drupal is retarded for doing something like that: https://www.drupal.org/node/2150267 ?

Also Symfony, Laravel and almost every other frameworks are retarded.

PHP-FIG is retarded too for saying something like 
> Direct usage of superglobals has a number of concerns. First, these are mutable, which makes it possible for libraries and code to alter the values, and thus alter state for the application. Additionally, superglobals make unit and integration testing difficult and brittle, leading to code quality degradation.
- https://www.php-fig.org/psr/psr-7/meta/

If you feel insulted when a piece of code advise you to write better code, you need to grow up or change career. But when you come bitching and insulting an author that made an amazing job creating a free plugin that is useful for me and other because it doesn't suit YOUR needs when you can disable the inspection with 3 clicks, it's just a sign you need to be a better human.

**Comment by coins2yap** [comment]
"So, your argument for example is that Drupal is retarded for doing something like that: https://www.drupal.org/node/2150267 ?"

No, that isn't my argument.

Your example is one where the developers moved all references to the superglobals to a single class. This doesn't help your case at all. It's probably pretty smart to move them one source tree because it makes the code cleaner in the rest of the project and can prevent developers from overwriting values that a project might want to be more strictly controlled. But it isn't removing the use of super globals, just abstracting them. And if one was coding this project, while editing the classes where the real superglobals  are being used and updated, he would be told that their mere use are wrong because they are deprecated globals. It also wouldn't technically prevent anyone from directly accessing the superglobals anywhere else in the project. That can't be enforced.

I'm not offended when somebody tells me to write better code if they have actually looked at my code and can discover the errors or poor patterns. What offends me is when somebody has been informed that his code is clearly in error and rather than fixing the problem he lashes out at people who politely tried to point out his error.

This plugin is not correct in pointing out that the use of a superglobal is wrong because a 'global' by that name is deprecated. There is no deprecation occurring. The warning is false. Period. It's their project, they don't have to fix anything they don't want. But they don't get to claim the warning is reporting correct information without challenge.

**Comment by orklah** [comment]
Your whole block about why it's smart to abstract access to superglobals is the whole reason why the inspection exists.

He made a few mistakes in his choices of word 'globals' => 'superglobals', "deprecated" => "discouraged" but who cares?

**Comment by funivan** [comment]
Hello @coins2yap 

> I'm not going to disable the inspection because there is no ability to do so.

1) You can disable this specific inspection
![image](https://user-images.githubusercontent.com/425208/125046674-e9678280-e0a6-11eb-8dd0-cb6f662c6e28.png)


2) Imagine that you will see another name for this inspection like: `GlobalVariableUsage` and in the IDE you will be informed that global state is bad and you likely need to rewrite the code. Will it work for you?

**Comment by funivan** [comment]
Hey folks. Thanks for your feedback. You are right - globals are not deprecated. 
I will update the description message for this inspection to avoid confusion in the future. https://github.com/funivan/PhpClean/pull/150
